### Register a user
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
  "username": "jerrel",
  "password": "1234",
  "name": "bob",
  "email": "test@example.com",
  "phone": "1234567890",
  "birth_year": "2002"
}
###
DELETE http://127.0.0.1:8000/parking-lots/9999999/force
Authorization: Bearer {{token}}

### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "superadmin",
  "password": "admin123"
}

###
@token = {{login.response.body.access_token}}

### GET USER DETAILS (7.1)
GET http://127.0.0.1:8000/profile
Authorization: Bearer {{token}}

###
# Create a vehicle for an user
POST http://127.0.0.1:8000/vehicles/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "license_plate": "45-ASP-1",
    "make": "Opal",
    "model": "308",
    "color": "Blue",
    "year": 2022
}

### Create a new parking lot (admin only)
POST http://127.0.0.1:8000/parking-lots
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Central Parking",
  "location": "Amsterdam",
  "address": "Damrak 1, 1012 LG Amsterdam",
  "capacity": 150,
  "tariff": 3.5,
  "daytariff": 25.0,
  "lat": 52.3676,
  "lng": 4.9041
}

### CREATE RESERVATION FOR USER (7.3)
POST http://127.0.0.1:8000/reservations/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "vehicle_id": 1,
  "parking_lot_id": 1,
  "start_time": "2026-01-01T10:00:00",
  "end_time": "2026-01-01T12:00:00",
  "discount_code": "discount"
}

###
POST http://127.0.0.1:8000/sessions/reservations/1/start
Content-Type: application/json
Authorization: Bearer {{token}}

{}

###
POST http://127.0.0.1:8000/sessions/reservations/1/stop
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### DELETE RESERVATION (7.4)
DELETE http://127.0.0.1:8000/admin/reservations/1
Authorization: Bearer {{token}}

###

### DELETE USER (1.6)
DELETE http://127.0.0.1:8000/admin/users/2
Authorization: Bearer {{token}}
### Get current user payments
GET http://127.0.0.1:8000/payments/me
Authorization: Bearer {{token}}
###
POST http://localhost:8000/parking-lots/1/sessions/start?vehicle_id=1
Authorization: Bearer {{token}}
### Get current sessions
GET http://localhost:8000/sessions/active
Authorization: Bearer {{token}}
### Get current sessions of a vehicle
GET http://localhost:8000/sessions/vehicle/1
Authorization: Bearer {{token}}
### Stop a session
POST http://localhost:8000/parking-lots/1/sessions/stop?vehicle_id=1
Authorization: Bearer {{token}}
###
POST http://localhost:8000/discount-codes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "discount",
  "user_id": 1,
  "discount_type": "percentage",
  "discount_value": 1.555,
  "use_amount": 100,
  "minimum_price": 10,
  "locations": []
}

###
GET http://localhost:8000/discount-codes
Authorization: Bearer {{token}}
###

GET http://localhost:8000/discount-codes/active
Authorization: Bearer {{token}}
###
GET http://localhost:8000/discount-codes/test5544
Authorization: Bearer {{token}}
###
POST http://localhost:8000/discount-codes/test5544/deactivate
Content-Type: application/json
Authorization: Bearer {{token}}

{}
###
DELETE http://localhost:8000/discount-codes/bla
Authorization: Bearer {{token}}