### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "superadmin",
  "password": "admin123"
}


###
@token = {{login.response.body.access_token}}


###


### Register an admin
POST http://127.0.0.1:8000/create_user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "admin2",
  "password": "admin",
  "name": "bob",
  "email": "test@example.com",
  "phone": "1234567890",
  "birth_year": "2002",
  "role": "lotadmin"
}

### Get all parking lots        oud
GET http://127.0.0.1:8000/get_user/2
Authorization: Bearer {{token}}


### Logout
POST http://127.0.0.1:8000/logout
Authorization: Bearer {{token}}


### Create a new parking lot (admin only)
POST http://127.0.0.1:8000/parking-lots
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Central Parking",
  "location": "Amsterdam",
  "address": "Damrak 1, 1012 LG Amsterdam",
  "capacity": 150,
  "tariff": 3.5,
  "daytariff": 25.0,
  "lat": 52.3676,
  "lng": 4.9041
}


### Get all parking lots        oud
GET http://127.0.0.1:8000/parking-lots/
Authorization: Bearer {{token}}


### Assign parking lot to admin (superadmin only)
POST http://127.0.0.1:8000/admin/2/parking-lots/1/assign
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### Logout
POST http://127.0.0.1:8000/logout
Authorization: Bearer {{token}}

### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin"
}


###
@token = {{login.response.body.access_token}}


### Get specific session from parking lot (admin only)
GET http://127.0.0.1:8000/parking-lots/1/sessions/1
Authorization: Bearer {{token}}


### Get specific session from parking lot (admin only)
GET http://127.0.0.1:8000/parking-lots/2/sessions/1
Authorization: Bearer {{token}}


### ---------------------------------------------------------user-----------------------------


### Register a user
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
  "username": "jerrel",
  "password": "1234",
  "name": "bob",
  "email": "test@example.com",
  "phone": "1234567890",
  "birth_year": "2002"
}

### Logout
POST http://127.0.0.1:8000/logout
Authorization: Bearer {{token}}

### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "jerrel",
  "password": "1234"
}


###
@token = {{login.response.body.access_token}}


###             oud
GET http://127.0.0.1:8000/payments/refunds
Authorization: Bearer {{token}}