### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "superadmin",
  "password": "admin123"
}


###
@token = {{login.response.body.access_token}}


### Register an admin
POST http://127.0.0.1:8000/create_admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "admin2",
  "password": "admin",
  "name": "bob",
  "email": "test@example.com",
  "phone": "1234567890",
  "birth_year": "2002",
  "role": "admin"
}


### Logout
POST http://127.0.0.1:8000/logout
Authorization: Bearer {{token}}

### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin"
}


###
@token = {{login.response.body.access_token}}


### Register a user
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
  "username": "jerrel",
  "password": "1234",
  "name": "bob",
  "email": "test@example.com",
  "phone": "1234567890",
  "birth_year": "2002"
}


### Login
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "jerrel",
  "password": "1234"
}


###
@token = {{login.response.body.access_token}}
