POST http://127.0.0.1:8000/payments/
Content-Type: application/json

{
  "user_id": 1,
  "transaction": "TXN-ABC-123",
  "amount": 12.50,
  "hash": "somehashvalue123",
  "method": "ideal",
  "issuer": "Rabobank",
  "bank": "RABO"
}
###
GET http://127.0.0.1:8000/payments/user/1
###