# Create a reservation
POST http://127.0.0.1:8000/create_reservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjQxMDE4NTN9._Px-KlyLkyMrvFNJJHvIEo1_gJKjk6hkoFle5qLw0f8

{
    "vehicle_id": 2,
    "parking_lot_id": 1,
    "start_date": "2025-11-26T09:00:00",
    "end_date": "2025-11-26T18:00:00"
}

### Get all reservations by ID vehicle.
GET http://127.0.0.1:8000/reservations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjQxMDE4NTN9._Px-KlyLkyMrvFNJJHvIEo1_gJKjk6hkoFle5qLw0f8
