# Create a vehicle for an user
POST http://127.0.0.1:8000/vehicles/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s

{
    "license_plate": "45-ASP-1",
    "make": "Opal",
    "model": "308",
    "color": "Blue",
    "year": 2022
}

### Get all vehicles.
GET http://127.0.0.1:8000/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s

### Get one vehicle.
GET http://127.0.0.1:8000/vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s

### Get vehicles of an user. (only for Admin)
GET http://127.0.0.1:8000/vehicles/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s

### Users must see the history of the vehicles reservations.
GET http://127.0.0.1:8000/vehicles/history-reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s

### Update a vehicle.
PUT http://127.0.0.1:8000/vehicles/update/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s
Content-Type: application/json

{
    "id": 1,
    "user_id": 1,
    "license_plate": "45-ASP-1",
    "make": "Opal",
    "model": "308",
    "color": "Red",
    "year": 2022
}

### Delete a vehicle.
DELETE http://127.0.0.1:8000/vehicles/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXJyZWwiLCJleHAiOjE3NjMzODU1OTB9.39CjP4Ewj2AxYC_1gw7XkA4uDsG3NkP5_K12z6u9Y8s